version: 0.2

phases: 
  install:
    commands:
      - git clone https://github.com/vegitable/nightwatch-testing-service.git
      - cd nightwatch-testing-service
      - apt-get install libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev
      - npm install
  pre_build:
    commands:
      - export NIGHTWATCH_URL=http://reactuiserviceprod.eu-west-2.elasticbeanstalk.com
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo "Build has completed."